version: 3.2.{build}
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
environment:
  key:
    secure: G4yxuYKkPftFKBlGFWvgu92cq+AmVfbUZwX8DMQEnkHufc7MIFH3u5qyQZQfzXOZ
build_script:
- ps: dotnet build -c Release
before_test:
- ps: | 
    dotnet publish -c Release -o out -f net6.0
    docker build -t autoapi . 
    docker run -d -p 5000:5000 autoapi
test_script:
- ps: dotnet test (Get-ChildItem out -File *Tests.dll | % { $_.FullName }) /logger:"console;verbosity=detailed"
    

deploy_script:
- ps: >-
    if($env:appveyor_repo_branch -eq 'master' -and $env:appveyor_repo_tag -eq "true") {
       dotnet nuget push ".\AutoAPI\bin\Release\Auto.Rest.API.$Env:APPVEYOR_BUILD_VERSION.nupkg" -s nuget.org -k $Env:key
    }
