version: 1.1.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
environment:
  key:
    secure: 2ymWtJQhQh/Xl3ik2l+QeJ0uIdIaCPdkpIGPnxPGHmfSiLNdWapPX64E2dWVBXeF
before_build:
- ps: nuget restore
build_script:
- ps: dotnet build -c Release
before_test:
- ps: dotnet publish -c Release -o out ; docker build -t autoapi . ; docker run -d -p 5000:5000 autoapi ; Start-Sleep -Seconds 20 
deploy_script:
- ps: >-
    if($env:appveyor_repo_branch -eq 'master') {
       dotnet nuget push ".\AutoAPI\bin\Release\Auto.Rest.API.$Env:APPVEYOR_BUILD_VERSION.nupkg" -s nuget.org -k $Env:key
    }
